// ============================================================
// PROFUMOTIFY v10.2 - DATABASE COMPLETO
// Collezione di Giancarlo - Bari
// 49 profumi reali con note olfattive, famiglie, immagini, link acquisto
// ============================================================

const perfumeDB = [
{
    id: 1, code: "PF001", name: "Cool Water", brand: "Davidoff",
    type: "designer",
    concentration: "EDT", gender: "Uomo", year: 1988,
    olfactoryFamily: "Aromatico Acquatico",
    topNotes: ["Menta", "Lavanda", "Coriandolo", "Rosmarino", "Calone"],
    heartNotes: ["Gelsomino", "Geranio", "Neroli", "Sandalo"],
    baseNotes: ["Muschio", "Ambra", "Cedro", "Tabacco"],
    season: ["Estate", "Primavera"], occasion: "Casual / Giorno",
    longevity: 6, sillage: 6, value: 9,
    rating: 10,
    intensity: 9,
    price: 30.0, size: "125ml",
    image: "https://fimgs.net/mdimg/perfume/375x500.507.jpg",
    fragrantica: "https://www.fragrantica.com/perfume/Davidoff/Cool-Water-507.html",
    notino: "https://www.notino.it/davidoff/cool-water-eau-de-toilette-eau-de-toilette-per-uomo/p-16378998",
    pinalli: "https://www.pinalli.it/products/profumi-cool-water-1bey00cws3",
    description: "Icona marina fresca e pulita. Il profumo dell'oceano."
  },
{
    id: 2, code: "PF002", name: "Cool Water Intense", brand: "Davidoff",
    type: "designer",
    concentration: "EDP", gender: "Uomo", year: 2019,
    olfactoryFamily: "Orientale Acquatico",
    topNotes: ["Mandorla verde", "Mandarino", "Ananas"],
    heartNotes: ["Cocco", "Fiore di tiarè", "Miele"],
    baseNotes: ["Vaniglia", "Muschio", "Ambra", "Legno di sandalo"],
    season: ["Estate", "Primavera", "Autunno"], occasion: "Casual / Serata",
    longevity: 7, sillage: 7, value: 8,
    rating: 9,
    intensity: 8,
    price: 35.0, size: "125ml",
    image: "https://fimgs.net/mdimg/perfume/375x500.55266.jpg",
    fragrantica: "https://www.fragrantica.com/perfume/Davidoff/Cool-Water-Intense-55266.html",
    notino: "https://www.notino.it/davidoff/davidoff-cool-water-intense-eau-de-parfum-per-uomo-125-ml/",
    pinalli: "https://www.pinalli.it/search?q=Davidoff+Cool+Water+Intense",
    description: "Versione intensa e dolce del classico Cool Water."
  },
{
    id: 3, code: "PF003", name: "Artisan Pure", brand: "John Varvatos",
    type: "designer",
    concentration: "EDT", gender: "Uomo", year: 2017,
    olfactoryFamily: "Citrus Aromatico",
    topNotes: ["Cedro", "Mandarino", "Bergamotto", "Limone", "Timo"],
    heartNotes: ["Gelsomino", "Ginger", "Arancio amaro"],
    baseNotes: ["Muschio", "Ambra", "Legno di cedro", "Radice di iris"],
    season: ["Primavera", "Estate"], occasion: "Casual / Ufficio",
    longevity: 6, sillage: 5, value: 8,
    rating: 9,
    intensity: 8,
    price: 42.5, size: "125ml",
    image: "https://fimgs.net/mdimg/perfume/375x500.46623.jpg",
    fragrantica: "https://www.fragrantica.com/perfume/John-Varvatos/Artisan-Pure-46623.html",
    notino: "https://www.notino.it/john-varvatos/artisan-pure-eau-de-toilette-per-uomo/",
    pinalli: "https://www.pinalli.it/search?q=John+Varvatos+Artisan+Pure",
    description: "Citrus fresco e pulito, elegante e naturale."
  },
{
    id: 4, code: "PF004", name: "Individuel", brand: "Montblanc",
    type: "designer",
    concentration: "EDT", gender: "Uomo", year: 2003,
    olfactoryFamily: "Orientale Legnoso",
    topNotes: ["Coriandolo", "Bergamotto", "Mandarino", "Ananas", "Cannella"],
    heartNotes: ["Gelsomino", "Fiore d'arancio", "Muschio di quercia", "Geranio"],
    baseNotes: ["Vaniglia", "Muschio", "Cedro", "Ambra", "Patchouli"],
    season: ["Autunno", "Inverno"], occasion: "Ufficio / Casual",
    longevity: 7, sillage: 6, value: 9,
    rating: 10,
    intensity: 9,
    price: 30.0, size: "75ml",
    image: "https://fimgs.net/mdimg/perfume/375x500.4193.jpg",
    fragrantica: "https://www.fragrantica.com/perfume/Montblanc/Individuel-4193.html",
    notino: "https://www.notino.it/mont-blanc/individuel/",
    pinalli: "https://www.pinalli.it/search?q=Montblanc+Individuel",
    description: "Clone di Original Santal di Creed. Vaniglia e spezie."
  },
{
    id: 5, code: "PF005", name: "Momentum Intense", brand: "Bentley",
    type: "designer",
    concentration: "EDP", gender: "Uomo", year: 2017,
    olfactoryFamily: "Orientale Legnoso",
    topNotes: ["Bergamotto", "Lavanda", "Elemi"],
    heartNotes: ["Geranio", "Noce moscata", "Ambra", "Benzoino"],
    baseNotes: ["Muschio", "Legno di sandalo", "Cedro", "Ambra grigia"],
    season: ["Autunno", "Inverno"], occasion: "Serata / Formale",
    longevity: 8, sillage: 7, value: 9,
    rating: 10,
    intensity: 9,
    price: 35.0, size: "100ml",
    image: "https://fimgs.net/mdimg/perfume/375x500.43538.jpg",
    fragrantica: "https://www.fragrantica.com/perfume/Bentley/Momentum-Intense-43538.html",
    notino: "https://www.notino.it/bentley/momentum-intense-eau-de-parfum-per-uomo/",
    pinalli: "https://www.pinalli.it/search?q=Bentley+Momentum+Intense",
    description: "Pelle e spezie. Clone di Tuscan Leather di Tom Ford."
  },
{
    id: 6, code: "PF006", name: "Uomo Urban Feel", brand: "Salvatore Ferragamo",
    type: "designer",
    concentration: "EDT", gender: "Uomo", year: 2019,
    olfactoryFamily: "Aromatico Fougère",
    topNotes: ["Salvia sclarea", "Coffe", "Ambretta"],
    heartNotes: ["Pomodoro", "Salvia", "Ambra"],
    baseNotes: ["Muschio", "Cedro", "Vetiver", "Ambra"],
    season: ["Primavera", "Estate", "Autunno"], occasion: "Casual / Ufficio",
    longevity: 6, sillage: 5, value: 7,
    rating: 8,
    intensity: 7,
    price: 37.5, size: "100ml",
    image: "https://fimgs.net/mdimg/perfume/375x500.55367.jpg",
    fragrantica: "https://www.fragrantica.com/perfume/Salvatore-Ferragamo/Uomo-Salvatore-Ferragamo-Urban-Feel-55367.html",
    notino: "https://www.notino.it/search/?q=Salvatore+Ferragamo+Uomo+Urban+Feel",
    pinalli: "https://www.pinalli.it/search?q=Ferragamo+Urban+Feel",
    description: "Fougère moderno e urbano, fresco ma con carattere."
  },
{
    id: 7, code: "PF007", name: "One Million Lucky", brand: "Paco Rabanne",
    type: "designer",
    concentration: "EDT", gender: "Uomo", year: 2018,
    olfactoryFamily: "Orientale Legnoso",
    topNotes: ["Prugna", "Grapefruit", "Bergamotto"],
    heartNotes: ["Nocciola", "Miele", "Cedro", "Cashmere"],
    baseNotes: ["Legno di sandalo", "Ambra", "Muschio", "Legno di quercia"],
    season: ["Autunno", "Inverno"], occasion: "Serata / Festa",
    longevity: 8, sillage: 8, value: 7,
    rating: 8,
    intensity: 7,
    price: 60.0, size: "100ml",
    image: "https://fimgs.net/mdimg/perfume/375x500.48903.jpg",
    fragrantica: "https://www.fragrantica.com/perfume/Rabanne/1-Million-Lucky-48903.html",
    notino: "https://www.notino.it/paco-rabanne/1-million-lucky-eau-de-toilette-per-uomo/",
    pinalli: "https://www.pinalli.it/search?q=One+Million+Lucky",
    description: "Dolce e gourmand con prugna e nocciola. Forte e sexy."
  },
{
    id: 8, code: "PF008", name: "Eros", brand: "Versace",
    type: "designer",
    concentration: "EDT", gender: "Uomo", year: 2012,
    olfactoryFamily: "Aromatico Fougère",
    topNotes: ["Menta", "Mela verde", "Limone", "Bergamotto"],
    heartNotes: ["Tonka", "Ambroxan", "Geranio"],
    baseNotes: ["Vaniglia", "Muschio", "Cedro", "Vetiver"],
    season: ["Autunno", "Inverno", "Primavera"], occasion: "Serata / Festa",
    longevity: 8, sillage: 9, value: 8,
    rating: 9,
    intensity: 8,
    price: 50.0, size: "100ml",
    image: "https://fimgs.net/mdimg/perfume/375x500.16657.jpg",
    fragrantica: "https://www.fragrantica.com/perfume/Versace/Eros-16657.html",
    notino: "https://www.notino.it/versace/eros-eau-de-toilette-per-uomo/",
    pinalli: "https://www.pinalli.it/search?q=Versace+Eros",
    description: "Potente e seducente. Menta, mela e vaniglia. Clubbing."
  },
{
    id: 9, code: "PF009", name: "Wanted By Night", brand: "Azzaro",
    type: "designer",
    concentration: "EDP", gender: "Uomo", year: 2018,
    olfactoryFamily: "Orientale Speziato",
    topNotes: ["Mandarino", "Limone", "Cannella", "Noce moscata"],
    heartNotes: ["Cedro", "Incenso", "Cumino", "Cedro rosso"],
    baseNotes: ["Cedro", "Vaniglia", "Muschio", "Cumino", "Legno di cedro"],
    season: ["Autunno", "Inverno"], occasion: "Serata / Formale",
    longevity: 8, sillage: 8, value: 8,
    rating: 9,
    intensity: 8,
    price: 52.5, size: "100ml",
    image: "https://fimgs.net/mdimg/perfume/375x500.49144.jpg",
    fragrantica: "https://www.fragrantica.com/perfume/Azzaro/Wanted-by-Night-49144.html",
    notino: "https://www.notino.it/azzaro/wanted-by-night-eau-de-parfum-per-uomo/",
    pinalli: "https://www.pinalli.it/search?q=Azzaro+Wanted+By+Night",
    description: "Speziato e caldo per la notte. Cannella e incenso."
  },
{
    id: 10, code: "PF010", name: "Rouat Al Oud", brand: "Lattafa",
    type: "arab",
    concentration: "EDP", gender: "Unisex", year: 2020,
    olfactoryFamily: "Orientale Legnoso",
    topNotes: ["Oud", "Rosa", "Zafferano", "Pepe nero"],
    heartNotes: ["Patchouli", "Agarwood", "Gelsomino"],
    baseNotes: ["Muschio", "Ambra", "Legno di sandalo", "Vaniglia"],
    season: ["Autunno", "Inverno"], occasion: "Formale / Serata",
    longevity: 9, sillage: 8, value: 9,
    rating: 10,
    intensity: 9,
    price: 20.0, size: "100ml",
    image: "https://fimgs.net/mdimg/perfume/375x500.71251.jpg",
    fragrantica: "https://www.fragrantica.com/perfume/Lattafa-Perfumes/Rouat-Al-Oud-71251.html",
    notino: "https://www.notino.it/search/?q=Lattafa+Rouat+Al+Oud",
    pinalli: "https://www.pinalli.it/search?q=Lattafa+Rouat+Al+Oud",
    description: "Oud ricco e rosa. Clone di Oud Satin Mood di MFK."
  },
{
    id: 11, code: "PF011", name: "Confidential Platinum", brand: "Lattafa",
    type: "arab",
    concentration: "EDP", gender: "Uomo", year: 2021,
    olfactoryFamily: "Orientale Legnoso",
    topNotes: ["Bergamotto", "Pepe rosa", "Cardamomo"],
    heartNotes: ["Lavanda", "Geranio", "Iris"],
    baseNotes: ["Legno di sandalo", "Muschio", "Ambra", "Vaniglia"],
    season: ["Autunno", "Inverno", "Primavera"], occasion: "Ufficio / Formale",
    longevity: 8, sillage: 7, value: 9,
    rating: 10,
    intensity: 9,
    price: 20.0, size: "100ml",
    image: "https://fimgs.net/mdimg/perfume/375x500.78549.jpg",
    fragrantica: "https://www.fragrantica.com/perfume/Lattafa-Perfumes/Confidential-Platinum-78549.html",
    notino: "https://www.notino.it/lattafa/confidential-platinum-eau-de-parfum-unisex/",
    pinalli: "https://www.pinalli.it/search?q=Lattafa+Confidential+Platinum",
    description: "Elegante e moderno. Clone di Platinum 24 by Lattafa."
  },
{
    id: 12, code: "PF012", name: "Maahir Black Edition", brand: "Lattafa",
    type: "arab",
    concentration: "EDP", gender: "Uomo", year: 2021,
    olfactoryFamily: "Orientale Speziato",
    topNotes: ["Pepe rosa", "Bergamotto", "Limone"],
    heartNotes: ["Lavanda", "Geranio", "Elemi", "Noce moscata"],
    baseNotes: ["Ambra", "Muschio", "Legno di cedro", "Vaniglia"],
    season: ["Autunno", "Inverno"], occasion: "Serata / Formale",
    longevity: 9, sillage: 8, value: 9,
    rating: 10,
    intensity: 9,
    price: 20.0, size: "100ml",
    image: "https://fimgs.net/mdimg/perfume/375x500.66564.jpg",
    fragrantica: "https://www.fragrantica.com/perfume/Lattafa-Perfumes/Maahir-Black-Edition-66564.html",
    notino: "https://www.notino.it/lattafa/maahir-black-edition-eau-de-parfum-unisex/",
    pinalli: "https://www.pinalli.it/search?q=Lattafa+Maahir+Black+Edition",
    description: "Speziato intenso e misterioso. Clone di Bvlgari Tygar."
  },
{
    id: 13, code: "PF013", name: "Hayatim", brand: "Lattafa",
    type: "arab",
    concentration: "EDP", gender: "Unisex", year: 2021,
    olfactoryFamily: "Floreale Fruttato",
    topNotes: ["Mela", "Bergamotto", "Limone"],
    heartNotes: ["Rosa", "Gelsomino", "Lillà"],
    baseNotes: ["Muschio", "Ambra", "Vaniglia", "Legno di sandalo"],
    season: ["Primavera", "Estate"], occasion: "Casual / Giorno",
    longevity: 7, sillage: 6, value: 9,
    rating: 10,
    intensity: 9,
    price: 16.0, size: "100ml",
    image: "https://fimgs.net/mdimg/perfume/375x500.134606.jpg",
    fragrantica: "https://www.fragrantica.com/perfume/Lattafa-Perfumes/Hayatim-134606.html",
    notino: "https://www.notino.it/search/?q=Lattafa+Hayatim",
    pinalli: "https://www.pinalli.it/search?q=Lattafa+Hayaatim",
    description: "Fresco floreale-fruttato. Clone di Versace Dylan Blue."
  },
{
    id: 14, code: "PF014", name: "Oud Mood Silver", brand: "Lattafa",
    type: "arab",
    concentration: "EDP", gender: "Unisex", year: 2020,
    olfactoryFamily: "Orientale Legnoso",
    topNotes: ["Oud", "Rosa", "Zafferano"],
    heartNotes: ["Patchouli", "Incenso", "Gelsomino"],
    baseNotes: ["Muschio", "Ambra", "Vaniglia", "Legno di cedro"],
    season: ["Autunno", "Inverno"], occasion: "Formale / Serata",
    longevity: 9, sillage: 8, value: 9,
    rating: 10,
    intensity: 9,
    price: 20.0, size: "100ml",
    image: "https://fimgs.net/mdimg/perfume/375x500.72718.jpg",
    fragrantica: "https://www.fragrantica.com/perfume/Lattafa-Perfumes/Oud-Mood-Silver-72718.html",
    notino: "https://www.notino.it/search/?q=Lattafa+Oud+Mood+Silver",
    pinalli: "https://www.pinalli.it/search?q=Lattafa+Oud+Mood+Reminiscence",
    description: "Oud e rosa con incenso. Clone di Oud Wood di Tom Ford."
  },
{
    id: 15, code: "PF015", name: "Opulent Oud", brand: "Lattafa",
    type: "arab",
    concentration: "EDP", gender: "Unisex", year: 2018,
    olfactoryFamily: "Orientale Legnoso",
    topNotes: ["Oud", "Zafferano", "Pepe nero"],
    heartNotes: ["Rosa", "Patchouli", "Incenso"],
    baseNotes: ["Muschio", "Ambra", "Vaniglia", "Legno di sandalo"],
    season: ["Autunno", "Inverno"], occasion: "Formale / Serata",
    longevity: 9, sillage: 8, value: 9,
    rating: 10,
    intensity: 9,
    price: 20.0, size: "100ml",
    image: "https://fimgs.net/mdimg/perfume/375x500.66012.jpg",
    fragrantica: "https://www.fragrantica.com/perfume/Lattafa-Perfumes/Opulent-Oud-66012.html",
    notino: "https://www.notino.it/lattafa/opulent-oud-eau-de-parfum-unisex/",
    pinalli: "https://www.pinalli.it/search?q=Lattafa+Opulent+Oud",
    description: "Oud opulento e speziato. Clone di Tom Ford Oud Wood."
  },
{
    id: 16, code: "PF016", name: "Dalia Rouge Extrait", brand: "Adyan",
    type: "arab",
    concentration: "Extrait", gender: "Unisex", year: 2022,
    olfactoryFamily: "Orientale Gourmand",
    topNotes: ["Mandorla", "Zafferano", "Pepe rosa"],
    heartNotes: ["Rosa", "Gelsomino", "Liquirizia"],
    baseNotes: ["Muschio", "Ambra", "Vaniglia", "Oud"],
    season: ["Autunno", "Inverno"], occasion: "Formale / Serata",
    longevity: 10, sillage: 9, value: 9,
    rating: 10,
    intensity: 9,
    price: 25.0, size: "100ml",
    image: "",
    fragrantica: "https://www.fragrantica.com/search/?q=Adyan+Dalia+Rouge+Extrait",
    notino: "https://www.notino.it/search/?q=Adyan+Dalia+Rouge+Extrait",
    pinalli: "https://www.pinalli.it/search?q=Adyan+Dalia+Rouge",
    description: "Gourmand intenso con mandorla e zafferano. Clone di BR540."
  },
{
    id: 17, code: "PF017", name: "Ajwad", brand: "Lattafa",
    type: "arab",
    concentration: "EDP", gender: "Unisex", year: 2021,
    olfactoryFamily: "Orientale Fruttato",
    topNotes: ["Mela", "Bergamotto", "Limone"],
    heartNotes: ["Rosa", "Gelsomino", "Lillà"],
    baseNotes: ["Muschio", "Ambra", "Vaniglia", "Legno di sandalo"],
    season: ["Primavera", "Estate"], occasion: "Casual / Giorno",
    longevity: 7, sillage: 6, value: 9,
    rating: 10,
    intensity: 9,
    price: 20.0, size: "100ml",
    image: "https://fimgs.net/mdimg/perfume/375x500.75099.jpg",
    fragrantica: "https://www.fragrantica.com/perfume/Lattafa-Perfumes/Ajwad-75099.html",
    notino: "https://www.notino.it/search/?q=Lattafa+Ajwad",
    pinalli: "https://www.pinalli.it/search?q=Lattafa+Ajwad",
    description: "Fruttato-floreale fresco. Clone di Versace Eros."
  },
{
    id: 18, code: "PF018", name: "Club de Nuit Sillage", brand: "Armaf",
    type: "arab",
    concentration: "EDP", gender: "Unisex", year: 2020,
    olfactoryFamily: "Floreale Acquatico",
    topNotes: ["Bergamotto", "Limone", "Mandarino", "Neroli"],
    heartNotes: ["Gelsomino", "Rosa", "Fiore d'arancio", "Curcuma"],
    baseNotes: ["Muschio", "Ambra", "Legno di sandalo", "Cedro"],
    season: ["Primavera", "Estate"], occasion: "Casual / Ufficio",
    longevity: 8, sillage: 8, value: 9,
    rating: 10,
    intensity: 9,
    price: 25.0, size: "105ml",
    image: "https://fimgs.net/mdimg/perfume/375x500.64105.jpg",
    fragrantica: "https://www.fragrantica.com/perfume/Armaf/Club-de-Nuit-Sillage-64105.html",
    notino: "https://www.notino.it/armaf/club-de-nuit-sillage-eau-de-parfum-per-uomo/",
    pinalli: "https://www.pinalli.it/search?q=Armaf+Club+de+Nuit+Sillage",
    description: "Clone di Silver Mountain Water di Creed. Fresco e floreale."
  },
{
    id: 19, code: "PF019", name: "Q Intense", brand: "Armaf",
    type: "arab",
    concentration: "EDP", gender: "Uomo", year: 2021,
    olfactoryFamily: "Orientale Speziato",
    topNotes: ["Pepe rosa", "Bergamotto", "Cardamomo"],
    heartNotes: ["Lavanda", "Geranio", "Noce moscata"],
    baseNotes: ["Legno di sandalo", "Muschio", "Ambra", "Vaniglia"],
    season: ["Autunno", "Inverno"], occasion: "Serata / Formale",
    longevity: 8, sillage: 7, value: 9,
    rating: 10,
    intensity: 9,
    price: 25.0, size: "100ml",
    image: "https://fimgs.net/mdimg/perfume/375x500.77376.jpg",
    fragrantica: "https://www.fragrantica.com/perfume/Armaf/Q-Intense-Eau-de-Parfum-77376.html",
    notino: "https://www.notino.it/armaf/q-intense-eau-de-parfum-per-uomo/",
    pinalli: "https://www.pinalli.it/search?q=Armaf+Q+Intense",
    description: "Speziato intenso. Clone di Bvlgari Man in Black."
  },
{
    id: 20, code: "PF020", name: "Ramz Silver", brand: "Lattafa",
    type: "arab",
    concentration: "EDP", gender: "Uomo", year: 2021,
    olfactoryFamily: "Aromatico Fougère",
    topNotes: ["Menta", "Lavanda", "Bergamotto"],
    heartNotes: ["Geranio", "Gelsomino", "Ambra"],
    baseNotes: ["Muschio", "Cedro", "Vaniglia", "Vetiver"],
    season: ["Primavera", "Estate", "Autunno"], occasion: "Casual / Ufficio",
    longevity: 7, sillage: 7, value: 9,
    rating: 10,
    intensity: 9,
    price: 16.0, size: "100ml",
    image: "https://fimgs.net/mdimg/perfume/375x500.71868.jpg",
    fragrantica: "https://www.fragrantica.com/perfume/Lattafa-Perfumes/Ramz-Lattafa-Silver-71868.html",
    notino: "https://www.notino.it/search/?q=Lattafa+Ramz+Silver",
    pinalli: "https://www.pinalli.it/search?q=Lattafa+Ramz+Silver",
    description: "Fougère fresco e versatile. Clone di Dior Sauvage."
  },
{
    id: 21, code: "PF021", name: "Black Saffron", brand: "Armaf",
    type: "arab",
    concentration: "EDP", gender: "Unisex", year: 2021,
    olfactoryFamily: "Orientale Speziato",
    topNotes: ["Zafferano", "Pepe rosa", "Bergamotto"],
    heartNotes: ["Rosa", "Patchouli", "Incenso"],
    baseNotes: ["Oud", "Muschio", "Ambra", "Vaniglia"],
    season: ["Autunno", "Inverno"], occasion: "Formale / Serata",
    longevity: 8, sillage: 7, value: 9,
    rating: 10,
    intensity: 9,
    price: 25.0, size: "100ml",
    image: "https://fimgs.net/mdimg/perfume/375x500.94311.jpg",
    fragrantica: "https://www.fragrantica.com/perfume/Armaf/Black-Saffron-94311.html",
    notino: "https://www.notino.it/armaf/black-saffron-eau-de-parfum-per-uomo/",
    pinalli: "https://www.pinalli.it/search?q=Armaf+Black+Saffron",
    description: "Zafferano e oud intenso. Clone di Tom Ford Black Saffron."
  },
{
    id: 22, code: "PF022", name: "Mohra", brand: "Lattafa",
    type: "arab",
    concentration: "EDP", gender: "Unisex", year: 2021,
    olfactoryFamily: "Orientale Speziato",
    topNotes: ["Pepe rosa", "Bergamotto", "Cardamomo"],
    heartNotes: ["Rosa", "Patchouli", "Incenso"],
    baseNotes: ["Oud", "Muschio", "Ambra", "Vaniglia"],
    season: ["Autunno", "Inverno"], occasion: "Formale / Serata",
    longevity: 9, sillage: 8, value: 9,
    rating: 10,
    intensity: 9,
    price: 20.0, size: "100ml",
    image: "https://fimgs.net/mdimg/perfume/375x500.78382.jpg",
    fragrantica: "https://www.fragrantica.com/perfume/Lattafa-Perfumes/Mohra-78382.html",
    notino: "https://www.notino.it/lattafa/mohra-eau-de-parfum-unisex/",
    pinalli: "https://www.pinalli.it/search?q=Lattafa+Mohra",
    description: "Speziato-oud intenso. Clone di Tom Ford Tuscan Leather."
  },
{
    id: 23, code: "PF023", name: "Qaed Al Fursan", brand: "Lattafa",
    type: "arab",
    concentration: "EDP", gender: "Uomo", year: 2021,
    olfactoryFamily: "Orientale Fruttato",
    topNotes: ["Mela", "Ananas", "Bergamotto"],
    heartNotes: ["Rosa", "Gelsomino", "Birch"],
    baseNotes: ["Muschio", "Ambra", "Vaniglia", "Legno di sandalo"],
    season: ["Autunno", "Inverno", "Primavera"], occasion: "Casual / Serata",
    longevity: 8, sillage: 8, value: 9,
    rating: 10,
    intensity: 9,
    price: 16.0, size: "100ml",
    image: "https://fimgs.net/mdimg/perfume/375x500.67996.jpg",
    fragrantica: "https://www.fragrantica.com/perfume/Lattafa-Perfumes/Qaed-Al-Fursan-67996.html",
    notino: "https://www.notino.it/search/?q=Lattafa+Qaed+Al+Fursan",
    pinalli: "https://www.pinalli.it/search?q=Lattafa+Qaed+Al+Fursan",
    description: "Fruttato intenso con birke. Clone di Creed Aventus."
  },
{
    id: 24, code: "PF024", name: "Oyuny", brand: "Al Haramain",
    type: "arab",
    concentration: "EDP", gender: "Unisex", year: 2021,
    olfactoryFamily: "Orientale Legnoso",
    topNotes: ["Oud", "Rosa", "Zafferano"],
    heartNotes: ["Patchouli", "Incenso", "Gelsomino"],
    baseNotes: ["Muschio", "Ambra", "Vaniglia", "Legno di sandalo"],
    season: ["Autunno", "Inverno"], occasion: "Formale / Serata",
    longevity: 9, sillage: 8, value: 9,
    rating: 10,
    intensity: 9,
    price: 20.0, size: "100ml",
    image: "https://fimgs.net/mdimg/perfume/375x500.48229.jpg",
    fragrantica: "https://www.fragrantica.com/perfume/Al-Haramain-Perfumes/Oyuny-48229.html",
    notino: "https://www.notino.it/search/?q=Al+Haramain+Oyuny",
    pinalli: "https://www.pinalli.it/search?q=Al+Haramain+Oyuny",
    description: "Oud e rosa con incenso. Clone di Oud Satin Mood."
  },
{
    id: 25, code: "PF025", name: "Jameel", brand: "Khadlaj",
    type: "arab",
    concentration: "EDP", gender: "Unisex", year: 2021,
    olfactoryFamily: "Orientale Fruttato",
    topNotes: ["Mela", "Bergamotto", "Limone"],
    heartNotes: ["Rosa", "Gelsomino", "Lillà"],
    baseNotes: ["Muschio", "Ambra", "Vaniglia", "Legno di sandalo"],
    season: ["Primavera", "Estate"], occasion: "Casual / Giorno",
    longevity: 7, sillage: 6, value: 9,
    rating: 10,
    intensity: 9,
    price: 20.0, size: "100ml",
    image: "",
    fragrantica: "https://www.fragrantica.com/search/?q=Khadlaj+Jameel",
    notino: "https://www.notino.it/search/?q=Khadlaj+Jameel",
    pinalli: "https://www.pinalli.it/search?q=Khadlaj+Jameel",
    description: "Fruttato-floreale fresco. Clone di Versace Dylan Blue."
  },
{
    id: 26, code: "PF026", name: "Aseel Al Oud", brand: "Khadlaj",
    type: "arab",
    concentration: "EDP", gender: "Unisex", year: 2021,
    olfactoryFamily: "Orientale Legnoso",
    topNotes: ["Oud", "Zafferano", "Pepe nero"],
    heartNotes: ["Rosa", "Patchouli", "Incenso"],
    baseNotes: ["Muschio", "Ambra", "Vaniglia", "Legno di cedro"],
    season: ["Autunno", "Inverno"], occasion: "Formale / Serata",
    longevity: 9, sillage: 8, value: 9,
    rating: 10,
    intensity: 9,
    price: 20.0, size: "100ml",
    image: "",
    fragrantica: "https://www.fragrantica.com/search/?q=Khadlaj+Aseel+Al+Oud",
    notino: "https://www.notino.it/search/?q=Khadlaj+Aseel+Al+Oud",
    pinalli: "https://www.pinalli.it/search?q=Khadlaj+Aseel+Al+Oud",
    description: "Oud puro e intenso. Clone di Oud Wood di Tom Ford."
  },
{
    id: 27, code: "PF027", name: "Teriaq Intense", brand: "Lattafa",
    type: "arab",
    concentration: "EDP", gender: "Unisex", year: 2023,
    olfactoryFamily: "Orientale Gourmand",
    topNotes: ["Miele", "Cannella", "Mandarino"],
    heartNotes: ["Vaniglia", "Tonka", "Caramello"],
    baseNotes: ["Muschio", "Ambra", "Legno di sandalo", "Oud"],
    season: ["Autunno", "Inverno"], occasion: "Serata / Formale",
    longevity: 9, sillage: 9, value: 9,
    rating: 10,
    intensity: 9,
    price: 20.0, size: "100ml",
    image: "https://fimgs.net/mdimg/perfume/375x500.99586.jpg",
    fragrantica: "https://www.fragrantica.com/perfume/Lattafa-Perfumes/Teriaq-Intense-99586.html",
    notino: "https://www.notino.it/search/?q=Lattafa+Teriaq+Intense",
    pinalli: "https://www.pinalli.it/search?q=Lattafa+Teriaq+Intense",
    description: "Gourmand dolce e intenso. Clone di Angels' Share di Kilian."
  },
{
    id: 28, code: "PF028", name: "Tanasuk", brand: "Al Haramain",
    type: "arab",
    concentration: "EDP", gender: "Unisex", year: 2021,
    olfactoryFamily: "Orientale Fruttato",
    topNotes: ["Mela", "Bergamotto", "Limone"],
    heartNotes: ["Rosa", "Gelsomino", "Lillà"],
    baseNotes: ["Muschio", "Ambra", "Vaniglia", "Legno di sandalo"],
    season: ["Primavera", "Estate"], occasion: "Casual / Giorno",
    longevity: 7, sillage: 6, value: 9,
    rating: 10,
    intensity: 9,
    price: 20.0, size: "100ml",
    image: "",
    fragrantica: "https://www.fragrantica.com/search/?q=Al+Haramain+Tanasuk",
    notino: "https://www.notino.it/search/?q=Al+Haramain+Tanasuk",
    pinalli: "https://www.pinalli.it/search?q=Al+Haramain+Tanasuk",
    description: "Fruttato-floreale fresco. Clone di Versace Dylan Blue."
  },
{
    id: 29, code: "PF029", name: "Jameela", brand: "Al Haramain",
    type: "arab",
    concentration: "EDP", gender: "Unisex", year: 2021,
    olfactoryFamily: "Floreale Orientale",
    topNotes: ["Rosa", "Gelsomino", "Bergamotto"],
    heartNotes: ["Ylang-ylang", "Fiore d'arancio", "Patchouli"],
    baseNotes: ["Muschio", "Ambra", "Vaniglia", "Legno di sandalo"],
    season: ["Primavera", "Estate"], occasion: "Casual / Giorno",
    longevity: 7, sillage: 6, value: 9,
    rating: 10,
    intensity: 9,
    price: 20.0, size: "100ml",
    image: "https://fimgs.net/mdimg/perfume/375x500.51822.jpg",
    fragrantica: "https://www.fragrantica.com/perfume/Al-Haramain-Perfumes/Jameela-51822.html",
    notino: "https://www.notino.it/search/?q=Al+Haramain+Jameela",
    pinalli: "https://www.pinalli.it/search?q=Al+Haramain+Jameela",
    description: "Floreale orientale delicato. Clone di Chanel Chance."
  },
{
    id: 30, code: "PF030", name: "Saher Al Layali", brand: "Ard Al Zaafaran",
    type: "arab",
    concentration: "EDP", gender: "Unisex", year: 2021,
    olfactoryFamily: "Orientale Legnoso",
    topNotes: ["Oud", "Rosa", "Zafferano"],
    heartNotes: ["Patchouli", "Incenso", "Gelsomino"],
    baseNotes: ["Muschio", "Ambra", "Vaniglia", "Legno di sandalo"],
    season: ["Autunno", "Inverno"], occasion: "Formale / Serata",
    longevity: 9, sillage: 8, value: 9,
    rating: 10,
    intensity: 9,
    price: 20.0, size: "100ml",
    image: "",
    fragrantica: "https://www.fragrantica.com/search/?q=Ard+Al+Zaafaran+Saher+Al+Layali",
    notino: "https://www.notino.it/ard-al-zaafaran/saher-al-layali-eau-de-parfum-unisex/",
    pinalli: "https://www.pinalli.it/search?q=Ard+Al+Zaafaran+Saher+Al+Layali",
    description: "Oud e rosa notturno. Clone di Oud Satin Mood."
  },
{
    id: 31, code: "PF031", name: "Salamah", brand: "Asdaaf",
    type: "arab",
    concentration: "EDP", gender: "Unisex", year: 2021,
    olfactoryFamily: "Orientale Legnoso",
    topNotes: ["Oud", "Zafferano", "Pepe nero"],
    heartNotes: ["Rosa", "Patchouli", "Incenso"],
    baseNotes: ["Muschio", "Ambra", "Vaniglia", "Legno di cedro"],
    season: ["Autunno", "Inverno"], occasion: "Formale / Serata",
    longevity: 9, sillage: 8, value: 9,
    rating: 10,
    intensity: 9,
    price: 20.0, size: "100ml",
    image: "",
    fragrantica: "https://www.fragrantica.com/search/?q=Asdaaf+Salamah",
    notino: "https://www.notino.it/search/?q=Asdaaf+Salamah",
    pinalli: "https://www.pinalli.it/search?q=Asdaaf+Salamah",
    description: "Oud speziato e intenso. Clone di Oud Wood."
  },
{
    id: 32, code: "PF032", name: "Sheikh Al Shuyukh Supreme", brand: "Lattafa",
    type: "arab",
    concentration: "EDP", gender: "Uomo", year: 2021,
    olfactoryFamily: "Orientale Legnoso",
    topNotes: ["Oud", "Zafferano", "Pepe nero"],
    heartNotes: ["Rosa", "Patchouli", "Incenso"],
    baseNotes: ["Muschio", "Ambra", "Vaniglia", "Legno di cedro"],
    season: ["Autunno", "Inverno"], occasion: "Formale / Serata",
    longevity: 9, sillage: 8, value: 9,
    rating: 10,
    intensity: 9,
    price: 20.0, size: "100ml",
    image: "https://fimgs.net/mdimg/perfume/375x500.110556.jpg",
    fragrantica: "https://www.fragrantica.com/perfume/Lattafa-Perfumes/Sheikh-Al-Shuyukh-Supreme-110556.html",
    notino: "https://www.notino.it/lattafa/sheikh-al-shuyukh-supreme-eau-de-parfum-unisex/",
    pinalli: "https://www.pinalli.it/search?q=Lattafa+Sheikh+Al+Shuyukh+Supreme",
    description: "Oud supremo e regale. Clone di Oud for Greatness di Initio."
  },
{
    id: 33, code: "PF033", name: "Najdia Intense", brand: "Lattafa",
    type: "arab",
    concentration: "EDP", gender: "Uomo", year: 2022,
    olfactoryFamily: "Aromatico Acquatico",
    topNotes: ["Menta", "Limone", "Bergamotto"],
    heartNotes: ["Lavanda", "Geranio", "Gelsomino"],
    baseNotes: ["Muschio", "Cedro", "Ambra", "Vetiver"],
    season: ["Estate", "Primavera"], occasion: "Casual / Giorno",
    longevity: 7, sillage: 7, value: 9,
    rating: 10,
    intensity: 9,
    price: 16.0, size: "100ml",
    image: "https://fimgs.net/mdimg/perfume/375x500.100128.jpg",
    fragrantica: "https://www.fragrantica.com/perfume/Lattafa-Perfumes/Najdia-Intense-100128.html",
    notino: "https://www.notino.it/lattafa/najdia-intense-eau-de-parfum-per-uomo/",
    pinalli: "https://www.pinalli.it/search?q=Lattafa+Najdia+Intense",
    description: "Acquatico intenso e fresco. Clone di Invictus Aqua."
  },
{
    id: 34, code: "PF034", name: "Petra", brand: "Lattafa",
    type: "arab",
    concentration: "EDP", gender: "Unisex", year: 2022,
    olfactoryFamily: "Orientale Legnoso",
    topNotes: ["Oud", "Rosa", "Zafferano"],
    heartNotes: ["Patchouli", "Incenso", "Gelsomino"],
    baseNotes: ["Muschio", "Ambra", "Vaniglia", "Legno di sandalo"],
    season: ["Autunno", "Inverno"], occasion: "Formale / Serata",
    longevity: 9, sillage: 8, value: 9,
    rating: 10,
    intensity: 9,
    price: 20.0, size: "100ml",
    image: "https://fimgs.net/mdimg/perfume/375x500.107089.jpg",
    fragrantica: "https://www.fragrantica.com/perfume/Lattafa-Perfumes/Petra-107089.html",
    notino: "https://www.notino.it/lattafa/petra-eau-de-parfum-unisex/",
    pinalli: "https://www.pinalli.it/search?q=Lattafa+Petra",
    description: "Oud e rosa con incenso. Clone di Rose Oud di MFK."
  },
{
    id: 35, code: "PF035", name: "Bateig Azul", brand: "Anfar London",
    type: "arab",
    concentration: "EDP", gender: "Uomo", year: 2021,
    olfactoryFamily: "Aromatico Acquatico",
    topNotes: ["Menta", "Limone", "Bergamotto"],
    heartNotes: ["Lavanda", "Geranio", "Gelsomino"],
    baseNotes: ["Muschio", "Cedro", "Ambra", "Vetiver"],
    season: ["Estate", "Primavera"], occasion: "Casual / Giorno",
    longevity: 7, sillage: 7, value: 9,
    rating: 10,
    intensity: 9,
    price: 20.0, size: "100ml",
    image: "https://fimgs.net/mdimg/perfume/375x500.99532.jpg",
    fragrantica: "https://www.fragrantica.com/perfume/Anfar-London/Bateig-Azul-99532.html",
    notino: "https://www.notino.it/search/?q=Anfar+Bateig+Azul",
    pinalli: "https://www.pinalli.it/search?q=Anfar+London+Bateig+Azul",
    description: "Acquatico blu fresco. Clone di Bleu de Chanel."
  },
{
    id: 36, code: "PF036", name: "Chef d'Oeuvre", brand: "Anfar London",
    type: "arab",
    concentration: "EDP", gender: "Unisex", year: 2022,
    olfactoryFamily: "Orientale Gourmand",
    topNotes: ["Miele", "Cannella", "Cardamomo"],
    heartNotes: ["Vaniglia", "Tonka", "Caramello"],
    baseNotes: ["Muschio", "Ambra", "Oud", "Legno di cedro"],
    season: ["Autunno", "Inverno"], occasion: "Serata / Formale",
    longevity: 9, sillage: 9, value: 9,
    rating: 10,
    intensity: 9,
    price: 25.0, size: "100ml",
    image: "https://fimgs.net/mdimg/perfume/375x500.106504.jpg",
    fragrantica: "https://www.fragrantica.com/perfume/Anfar-London/Chef-d-Oeuvre-106504.html",
    notino: "https://www.notino.it/search/?q=Anfar+London+Chef+d+Oeuvre",
    pinalli: "https://www.pinalli.it/search?q=Anfar+London+Chef+d+Oeuvre",
    description: "Gourmand intenso con miele. Clone di Angels' Share."
  },
{
    id: 37, code: "PF037", name: "Impulse Oud", brand: "Zimaya",
    type: "arab",
    concentration: "EDP", gender: "Unisex", year: 2022,
    olfactoryFamily: "Orientale Legnoso",
    topNotes: ["Oud", "Zafferano", "Pepe nero"],
    heartNotes: ["Rosa", "Patchouli", "Incenso"],
    baseNotes: ["Muschio", "Ambra", "Vaniglia", "Legno di cedro"],
    season: ["Autunno", "Inverno"], occasion: "Formale / Serata",
    longevity: 9, sillage: 8, value: 9,
    rating: 10,
    intensity: 9,
    price: 20.0, size: "100ml",
    image: "https://fimgs.net/mdimg/perfume/375x500.92580.jpg",
    fragrantica: "https://www.fragrantica.com/perfume/Zimaya/Impulse-Oud-92580.html",
    notino: "https://www.notino.it/search/?q=Zimaya+Impulse+Oud",
    pinalli: "https://www.pinalli.it/search?q=Zimaya+Impulse+Oud",
    description: "Oud impulsivo e speziato. Clone di Oud Wood."
  },
{
    id: 38, code: "PF038", name: "Soul Sea", brand: "LPDO",
    type: "designer",
    concentration: "EDP", gender: "Uomo", year: 2022,
    olfactoryFamily: "Aromatico Acquatico",
    topNotes: ["Menta", "Limone", "Bergamotto", "Sale marino"],
    heartNotes: ["Lavanda", "Geranio", "Gelsomino", "Alghe"],
    baseNotes: ["Muschio", "Cedro", "Ambra", "Vetiver"],
    season: ["Estate", "Primavera"], occasion: "Casual / Giorno",
    longevity: 6, sillage: 6, value: 8,
    rating: 9,
    intensity: 8,
    price: 30.0, size: "100ml",
    image: "https://fimgs.net/mdimg/perfume/375x500.101217.jpg",
    fragrantica: "https://www.fragrantica.com/perfume/LPDO/Soul-Sea-101217.html",
    notino: "https://www.notino.it/search/?q=LPDO+Soul+Sea",
    pinalli: "https://www.pinalli.it/search?q=LPDO+Soul+Sea",
    description: "Marino italiano fresco. Onda del mare Adriatico."
  },
{
    id: 39, code: "PF039", name: "Rubin Fumée", brand: "LPDO",
    type: "designer",
    concentration: "EDP", gender: "Uomo", year: 2022,
    olfactoryFamily: "Orientale Speziato",
    topNotes: ["Pepe rosa", "Bergamotto", "Cardamomo"],
    heartNotes: ["Lavanda", "Geranio", "Noce moscata"],
    baseNotes: ["Legno di sandalo", "Muschio", "Ambra", "Vaniglia"],
    season: ["Autunno", "Inverno"], occasion: "Serata / Formale",
    longevity: 7, sillage: 7, value: 8,
    rating: 9,
    intensity: 8,
    price: 30.0, size: "100ml",
    image: "https://fimgs.net/mdimg/perfume/375x500.81824.jpg",
    fragrantica: "https://www.fragrantica.com/perfume/LPDO/Rubin-Fumee-81824.html",
    notino: "https://www.notino.it/search/?q=LPDO+Rubin+Fumee",
    pinalli: "https://www.pinalli.it/search?q=LPDO+Rubin+Fumee",
    description: "Speziato fumoso italiano. Rubino e incenso."
  },
{
    id: 40, code: "PF040", name: "Hash Intense", brand: "LPDO",
    type: "designer",
    concentration: "EDP", gender: "Uomo", year: 2022,
    olfactoryFamily: "Orientale Legnoso",
    topNotes: ["Oud", "Cannabis", "Pepe nero"],
    heartNotes: ["Patchouli", "Incenso", "Caffè"],
    baseNotes: ["Muschio", "Ambra", "Vaniglia", "Legno di cedro"],
    season: ["Autunno", "Inverno"], occasion: "Serata / Formale",
    longevity: 8, sillage: 8, value: 8,
    rating: 9,
    intensity: 8,
    price: 30.0, size: "100ml",
    image: "https://fimgs.net/mdimg/perfume/375x500.59646.jpg",
    fragrantica: "https://www.fragrantica.com/perfume/LPDO/Hash-Intense-59646.html",
    notino: "https://www.notino.it/search/?q=LPDO+Hash+Intense",
    pinalli: "https://www.pinalli.it/search?q=LPDO+Hash+Intense",
    description: "Intenso e misterioso con cannabis. Notte italiana."
  },
{
    id: 41, code: "PF041", name: "Desert Doré", brand: "LPDO",
    type: "designer",
    concentration: "EDP", gender: "Unisex", year: 2022,
    olfactoryFamily: "Orientale Gourmand",
    topNotes: ["Miele", "Cannella", "Mandarino"],
    heartNotes: ["Vaniglia", "Tonka", "Caramello"],
    baseNotes: ["Muschio", "Ambra", "Oud", "Legno di sandalo"],
    season: ["Autunno", "Inverno"], occasion: "Serata / Formale",
    longevity: 8, sillage: 8, value: 8,
    rating: 9,
    intensity: 8,
    price: 30.0, size: "100ml",
    image: "https://fimgs.net/mdimg/perfume/375x500.109290.jpg",
    fragrantica: "https://www.fragrantica.com/perfume/LPDO/Desert-Dore-109290.html",
    notino: "https://www.notino.it/search/?q=LPDO+Desert+Dore",
    pinalli: "https://www.pinalli.it/search?q=LPDO+Desert+Dore",
    description: "Dorato gourmand del deserto. Sole e spezie."
  },
{
    id: 42, code: "PF042", name: "Gotique Island", brand: "LPDO",
    type: "designer",
    concentration: "EDP", gender: "Uomo", year: 2022,
    olfactoryFamily: "Aromatico Legnoso",
    topNotes: ["Bergamotto", "Limone", "Pino"],
    heartNotes: ["Lavanda", "Geranio", "Cedro"],
    baseNotes: ["Muschio", "Ambra", "Legno di sandalo", "Vetiver"],
    season: ["Autunno", "Inverno", "Primavera"], occasion: "Casual / Ufficio",
    longevity: 7, sillage: 6, value: 8,
    rating: 9,
    intensity: 8,
    price: 30.0, size: "100ml",
    image: "https://fimgs.net/mdimg/perfume/375x500.101216.jpg",
    fragrantica: "https://www.fragrantica.com/perfume/LPDO/Gotique-Island-101216.html",
    notino: "https://www.notino.it/search/?q=LPDO+Gotique+Island",
    pinalli: "https://www.pinalli.it/search?q=LPDO+Gotique+Island",
    description: "Legnoso gotico e fresco. Isola misteriosa."
  },
{
    id: 43, code: "PF043", name: "Man Blue Spirit", brand: "Zara",
    type: "designer",
    concentration: "EDT", gender: "Uomo", year: 2021,
    olfactoryFamily: "Aromatico Acquatico",
    topNotes: ["Menta", "Limone", "Bergamotto"],
    heartNotes: ["Lavanda", "Geranio", "Gelsomino"],
    baseNotes: ["Muschio", "Cedro", "Ambra", "Vetiver"],
    season: ["Estate", "Primavera"], occasion: "Casual / Giorno",
    longevity: 5, sillage: 5, value: 7,
    rating: 8,
    intensity: 7,
    price: 17.5, size: "100ml",
    image: "https://fimgs.net/mdimg/perfume/375x500.43468.jpg",
    fragrantica: "https://www.fragrantica.com/perfume/Zara/Man-Blue-Spirit-43468.html",
    notino: "https://www.notino.it/search/?q=Zara+Man+Blue+Spirit",
    pinalli: "https://www.pinalli.it/search?q=Zara+Man+Blue+Spirit",
    description: "Acquatico Zara fresco e accessibile."
  },
{
    id: 44, code: "PF044", name: "CK One Summer (Blu)", brand: "Calvin Klein",
    type: "designer",
    concentration: "EDT", gender: "Unisex", year: 2020,
    olfactoryFamily: "Citrus Aromatico",
    topNotes: ["Limone", "Bergamotto", "Mandarino", "Menta"],
    heartNotes: ["Gelsomino", "Geranio", "Lavanda"],
    baseNotes: ["Muschio", "Cedro", "Ambra"],
    season: ["Estate", "Primavera"], occasion: "Casual / Giorno",
    longevity: 5, sillage: 5, value: 7,
    rating: 8,
    intensity: 7,
    price: 30.0, size: "100ml",
    image: "https://fimgs.net/mdimg/perfume/375x500.59549.jpg",
    fragrantica: "https://www.fragrantica.com/perfume/Calvin-Klein/CK-One-Summer-2020-59549.html",
    notino: "https://www.notino.it/search/?q=Calvin+Klein+CK+One+Summer+2020",
    pinalli: "https://www.pinalli.it/search?q=CK+One+Summer+Blu",
    description: "Estate CK fresca e blu. Limone e mare."
  },
{
    id: 45, code: "PF045", name: "Deep", brand: "G. Bellini",
    type: "designer",
    concentration: "EDT", gender: "Uomo", year: 2020,
    olfactoryFamily: "Aromatico Fougère",
    topNotes: ["Menta", "Lavanda", "Bergamotto"],
    heartNotes: ["Geranio", "Gelsomino", "Ambra"],
    baseNotes: ["Muschio", "Cedro", "Vaniglia", "Vetiver"],
    season: ["Primavera", "Estate", "Autunno"], occasion: "Casual / Ufficio",
    longevity: 6, sillage: 6, value: 8,
    rating: 9,
    intensity: 8,
    price: 12.5, size: "100ml",
    image: "",
    fragrantica: "https://www.fragrantica.com/search/?q=G.+Bellini+Deep",
    notino: "https://www.notino.it/search/?q=G.+Bellini+Deep",
    pinalli: "https://www.pinalli.it/search?q=G+Bellini+Deep",
    description: "Fougère profondo low-cost. Clone di Dior Sauvage."
  },
{
    id: 46, code: "PF046", name: "Khamrah Qahwa", brand: "Lattafa",
    type: "arab",
    concentration: "EDP", gender: "Unisex", year: 2023,
    olfactoryFamily: "Orientale Gourmand",
    topNotes: ["Caffè", "Cannella", "Cardamomo"],
    heartNotes: ["Vaniglia", "Tonka", "Caramello"],
    baseNotes: ["Muschio", "Ambra", "Oud", "Legno di cedro"],
    season: ["Autunno", "Inverno"], occasion: "Serata / Formale",
    longevity: 9, sillage: 9, value: 9,
    rating: 10,
    intensity: 9,
    price: 20.0, size: "100ml",
    image: "https://fimgs.net/mdimg/perfume/375x500.88175.jpg",
    fragrantica: "https://www.fragrantica.com/perfume/Lattafa-Perfumes/Khamrah-Qahwa-88175.html",
    notino: "https://www.notino.it/lattafa/khamrah-qahwa-eau-de-parfum-unisex/",
    pinalli: "https://www.pinalli.it/search?q=Lattafa+Khamrah+Qahwa",
    description: "Caffè e spezie gourmand. Clone di Angels' Share."
  },
{
    id: 47, code: "PF047", name: "CK One", brand: "Calvin Klein",
    type: "designer",
    concentration: "EDT", gender: "Unisex", year: 1994,
    olfactoryFamily: "Citrus Aromatico",
    topNotes: ["Bergamotto", "Limone", "Mandarino", "Papaya"],
    heartNotes: ["Gelsomino", "Rosa", "Lily-of-the-valley", "Neroli"],
    baseNotes: ["Muschio", "Cedro", "Ambra", "Te verde"],
    season: ["Primavera", "Estate"], occasion: "Casual / Giorno",
    longevity: 5, sillage: 5, value: 8,
    rating: 9,
    intensity: 8,
    price: 25.0, size: "200ml",
    image: "https://fimgs.net/mdimg/perfume/375x500.276.jpg",
    fragrantica: "https://www.fragrantica.com/perfume/Calvin-Klein/CK-One-276.html",
    notino: "https://www.notino.it/calvin-klein/ck-one-eau-de-toilette-unisex/",
    pinalli: "https://www.pinalli.it/search?q=Calvin+Klein+CK+One",
    description: "Icona unisex degli anni '90. Fresco e pulito."
  },
{
    id: 48, code: "PF048", name: "CK One Summer (Arancio)", brand: "Calvin Klein",
    type: "designer",
    concentration: "EDT", gender: "Unisex", year: 2021,
    olfactoryFamily: "Citrus Fruttato",
    topNotes: ["Arancia", "Mandarino", "Bergamotto", "Limone"],
    heartNotes: ["Gelsomino", "Geranio", "Lavanda"],
    baseNotes: ["Muschio", "Cedro", "Ambra"],
    season: ["Estate", "Primavera"], occasion: "Casual / Giorno",
    longevity: 5, sillage: 5, value: 7,
    rating: 8,
    intensity: 7,
    price: 30.0, size: "100ml",
    image: "https://fimgs.net/mdimg/perfume/375x500.65799.jpg",
    fragrantica: "https://www.fragrantica.com/perfume/Calvin-Klein/CK-One-Summer-2021-65799.html",
    notino: "https://www.notino.it/search/?q=Calvin+Klein+CK+One+Summer+2021",
    pinalli: "https://www.pinalli.it/search?q=CK+One+Summer+Arancio",
    description: "Estate CK arancione e solare. Agrumi e sole."
  },
{
    id: 49, code: "PF049", name: "Ramz Gold", brand: "Lattafa",
    type: "arab",
    concentration: "EDP", gender: "Uomo", year: 2021,
    olfactoryFamily: "Orientale Fruttato",
    topNotes: ["Mela", "Ananas", "Bergamotto"],
    heartNotes: ["Rosa", "Gelsomino", "Birch"],
    baseNotes: ["Muschio", "Ambra", "Vaniglia", "Legno di sandalo"],
    season: ["Autunno", "Inverno", "Primavera"], occasion: "Casual / Serata",
    longevity: 8, sillage: 8, value: 9,
    rating: 10,
    intensity: 9,
    price: 16.0, size: "100ml",
    image: "https://fimgs.net/mdimg/perfume/375x500.70368.jpg",
    fragrantica: "https://www.fragrantica.com/perfume/Lattafa-Perfumes/Ramz-Lattafa-Gold-70368.html",
    notino: "https://www.notino.it/lattafa/ramz-gold-eau-de-parfum-unisex/",
    pinalli: "https://www.pinalli.it/search?q=Lattafa+Ramz+Gold",
    description: "Fruttato dorato intenso. Clone di Aventus."
  }
];

// ============================================================
// NOTE OLFATTIVE - MAPPING COMPLETO
// ============================================================
const noteCategories = {
  "Citrus": ["Bergamotto", "Limone", "Mandarino", "Arancia", "Pompelmo", "Neroli", "Cedro"],
  "Fruttato": ["Mela", "Ananas", "Prugna", "Papaya", "Mandarino", "Arancia"],
  "Floreale": ["Rosa", "Gelsomino", "Lavanda", "Geranio", "Lillà", "Fiore d'arancio", "Ylang-ylang", "Iris", "Neroli"],
  "Speziato": ["Cannella", "Pepe nero", "Pepe rosa", "Cardamomo", "Noce moscata", "Zafferano", "Cumino", "Curcuma", "Ginger"],
  "Legnoso": ["Legno di sandalo", "Cedro", "Legno di cedro", "Vetiver", "Pino", "Birch", "Legno di quercia"],
  "Orientale": ["Oud", "Agarwood", "Ambra", "Incenso", "Mirra", "Vaniglia", "Tonka"],
  "Gourmand": ["Vaniglia", "Tonka", "Caramello", "Miele", "Mandorla", "Caffè", "Cioccolato", "Nocciola"],
  "Muschiato": ["Muschio", "Ambra", "Muschio di quercia", "Cashmere"],
  "Aromatico": ["Menta", "Rosmarino", "Timo", "Salvia", "Lavanda", "Basilico"],
  "Acquatico": ["Calone", "Sale marino", "Alghe", "Acqua di mare"]
};

// ============================================================
// FAMIGLIE OLFATTIVE - COLORI E ICONA
// ============================================================
const familyStyles = {
  "Aromatico Acquatico": { color: "#00BCD4", icon: "🌊" },
  "Orientale Acquatico": { color: "#0097A7", icon: "🌊" },
  "Citrus Aromatico": { color: "#FF9800", icon: "🍊" },
  "Orientale Legnoso": { color: "#795548", icon: "🪵" },
  "Aromatico Fougère": { color: "#4CAF50", icon: "🌿" },
  "Orientale Speziato": { color: "#E65100", icon: "🌶️" },
  "Floreale Fruttato": { color: "#E91E63", icon: "🌸" },
  "Orientale Fruttato": { color: "#FF5722", icon: "🍎" },
  "Floreale Acquatico": { color: "#03A9F4", icon: "💧" },
  "Orientale Gourmand": { color: "#8D6E63", icon: "🍯" },
  "Floreale Orientale": { color: "#F06292", icon: "🌺" },
  "Aromatico Legnoso": { color: "#6D4C41", icon: "🌲" },
  "Citrus Fruttato": { color: "#FFB300", icon: "🍋" }
};

// ============================================================
// STAGIONI - MAPPING
// ============================================================
const seasonData = {
  "Primavera": { icon: "🌸", color: "#F8BBD0", months: [3,4,5] },
  "Estate": { icon: "☀️", color: "#FFF9C4", months: [6,7,8] },
  "Autunno": { icon: "🍂", color: "#FFE0B2", months: [9,10,11] },
  "Inverno": { icon: "❄️", color: "#E3F2FD", months: [12,1,2] }
};

// ============================================================
// DATI METEO BARI (stagionali medie)
// ============================================================
const bariWeather = {
  "Primavera": { temp: "18°C", humidity: "65%", condition: "Soleggiato", wind: "15 km/h", icon: "🌤️" },
  "Estate": { temp: "28°C", humidity: "70%", condition: "Caldo", wind: "12 km/h", icon: "☀️" },
  "Autunno": { temp: "20°C", humidity: "72%", condition: "Variabile", wind: "18 km/h", icon: "🌥️" },
  "Inverno": { temp: "12°C", humidity: "75%", condition: "Fresco", wind: "20 km/h", icon: "🌧️" }
};

// ============================================================
// CONSIGLI AUTOMATICI BASATI SU METEO + STAGIONE
// ============================================================
function getWeatherRecommendation(season, temp, humidity) {
  const recs = {
    "Estate": {
      hot: ["Aromatico Acquatico", "Citrus Aromatico", "Floreale Acquatico"],
      mild: ["Aromatico Fougère", "Citrus Fruttato", "Floreale Fruttato"]
    },
    "Primavera": {
      warm: ["Floreale Fruttato", "Citrus Aromatico", "Aromatico Fougère"],
      cool: ["Orientale Legnoso", "Aromatico Legnoso", "Floreale Orientale"]
    },
    "Autunno": {
      warm: ["Orientale Speziato", "Orientale Fruttato", "Aromatico Legnoso"],
      cool: ["Orientale Legnoso", "Orientale Gourmand", "Floreale Orientale"]
    },
    "Inverno": {
      cold: ["Orientale Gourmand", "Orientale Legnoso", "Orientale Speziato"],
      mild: ["Aromatico Fougère", "Orientale Fruttato", "Floreale Orientale"]
    }
  };
  return recs[season] || recs["Primavera"];
}

// Export CommonJS per gli script Node (es. controllo prezzi in GitHub Actions).
// Nel browser `module` non esiste, quindi questo blocco è un no-op.
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { perfumeDB, noteCategories, familyStyles, seasonData, bariWeather };
}